---

dist: focal
os: linux
language: python
python:
  - 3.6
  - 3.7
  - 3.8
  - 3.9
install:
  - pip install tox-travis
  - pip install wheel
  - pip install twine
script:
  - tox
deploy:
  provider: script
  on:
    tags: true
    python: 3.9
    condition: $TRAVIS_TAG =~ ^v.*$
  script: ./deploy.sh
env:
  global:
    - secure: "Zvf2uCntjh0UJN8XlDk03PXlWyY99cl91WVyyUu1o2hqb8bT5pbX7xWmbNiZ6mi6y5FnVoWeoXkedPlVgZZmSgM80BgEVBICi6HiZBB0Dm4QexbiTMk+SJMHztK7WMhdjT22OgcLBCmCQgmySlRc6S9WMyzSH7yGSfQ4ZTAeyhFDIbDAcQh1VKpze/RLneEZGX3KYpk0KC+JszJDE9ouXK8iIZ+e/068ZRvKTr200bM8VkJyRw0pIwSdu3gRDGT3ePjcsFQNrjzdZhSWcm0qApNazPGykv4i7bPGf8DMOo4XQZXDV7bd2SB1cOzZvn64RboVHY7RqxzCRsWeJek4C5m2bxs8tKhTZN3F/1VmrVUNkifqWO/O/0HmsYxNhb7DYJZkGwBuPgO+vxXL8h+AOXqE9JgvM6USyLesp0CeFV3Je/GIx+0mYyXikmip0Z5s5gc0JH+9WEAdrDa/GDJbHYn58NInRPOCvJdh5WIKAuUk/QEp2oMdiTbDDLv6fH64kcpZaln01Di0XRjRQfEj/c+feWckwRnzSNVNJ1V8XfGCEWJSoFz2X/l+gWqGxEe/5PRHRkMrxgOAaLdwd24rz2+KPe6hv49+o9AnF9aulfJJJMi2o0jRfA0GAlvBp8+q9fk84Rgw40ttllaSyCugmXsMRXk2nAVGdo4DiuUUCLY="
    - secure: "Mz2TncLe4MMDvbygXToAXuiiWl2RQjSIIL16waxXiBVkdKwK/EsDTEgR4lnjTzlSMzuElNKcORGe1952vmP9M7g6ZsL+LH9QyGokdCrxdBPRa8U1VzJkvLZZtalLwY9+xEXAJFtTVrPVmUHFOM6WrL1HHFkEMGKAqtAERiOOUZkARNgo80dtJpJvvEVC47Z4C81ydywwNJ0ycmz3K6+9MHdudR0zI7F1IvTuuuekhW/m5igFhjleOFq5sK22qece/ng2b2GZGNr4rAVhN5fu0Z77If9zaDffNW8UhjHFwKuSz6n1jtNT2wqKxVoq+GNT0azpDwfFLfg9fhEPR7BO1iMceyLeQK52b/SrwqiHGuBmgHZ5popsEJU9hvonyO944kJmG1lQ8b9TXwr+cLgJwDDNRyMgoxBLmnTZWgLZR3+hxTyDKPgiEsUFHFM/9Sv7qwj3s/jj3XMTHNqjN/EHKsAh9ulXxRk1kMH6litiyxtqB4Qtxs/+MZkRfIw0JEcd/NhE+/Y+wTmq1w0KIomZiKNKEbHPcLAdKXL2OtFzG4Dqrni8TmFReRvxM4p28Su0ljsIS8XujGnLuZ6yBu54NeElH5ZUlEr1tcZpifEIdxLLeRdZKF+vgLVclKAbXubo16qLk95DmgYS/cw3tL03aHYC0eNihH5IyAxMTiwEQxI="
