---
name: Build
on:
  - push
  - pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10']
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox tox-gh-actions
      - name: Test with tox
        run: tox
  publish:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.ref_protected }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Import GPG
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          fingerprint: 74C0C759C46E40BC421BC6DBDCCFEB9347EE8CC6
      - name: Build
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
          PYPI_REPOSITORY_URL: https://test.pypi.org/legacy/
        run: |
          python -m pip install --upgrade pip build twine
          python -m build --sdist --wheel
          twine upload -s -i httpieovhauth@gmail.com --repository-url "${{ env.PYPI_REPOSITORY_URL }}" dist/*
