---
name: Pypi publication
on:
  workflow_run:
    workflows:
      - Build
    types:
      - completed
  if: startsWith(github.ref, 'refs/tags/v')
jobs:
  publish-pypi:
    uses: ./.github/workflows/workflow-publish.yml
    with:
      environment: pypi
      publish_required: true
      sign_required: true
      sign_key_uuid: httpieovhauth@gmail.com
      pypi_repository_url: https://upload.pypi.org/legacy/
    secrets:
      pypi_token: ${{ secrets.PYPI_TOKEN }}
      sign_key: ${{ secrets.GPG_PRIVATE_KEY }}
      sign_key_passphrase: ${{ secrets.GPG_PASSPHRASE }}

